In [129]:
from sklearn.linear_model import LogisticRegression
import numpy as np
import pandas as pd
from patsy import dmatrices
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import PolynomialFeatures

In [130]:
dta = pd.read_csv("D:\MSc Computer Science - AR VR\Machine Learning\Twitter Gender Classification\ML-1819--task-107--team-32\ML-1819--task-107--team-32_cleanedUpDataTrainingSet.csv", ',')

In [131]:
Y_train = dta.iloc[:,1]
X_train = dta.iloc[:, 2:-1]

In [132]:
#dta['gender'] = (dta.gender == True).astype(int)

In [133]:
#dta.groupby('gender').mean()

In [134]:
#print (Y)

In [135]:
Y_train, X_train = dmatrices('gender ~ created + fav_number + tweet_count + descLen + des_hashtag_count + nameLen + tweet_length + '
                'num_tagged + tweet_hashtags + C(has_mentioned_other_bio) + C(uses_default_link_color) + '
                'C(tweet_has_link)', dta, return_type="dataframe")

In [136]:
Y_train = np.ravel(Y_train)

poly = PolynomialFeatures(2)
X_train = poly.fit_transform(X_train)

In [137]:
print (X_train)

[[1. 1. 0. ... 0. 0. 1.]
 [1. 1. 1. ... 4. 0. 0.]
 [1. 1. 0. ... 9. 0. 0.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 9. 3. 1.]]


In [138]:
# instantiate a logistic regression model, and fit with X and y
model = LogisticRegression(penalty = 'l2', C = 1000,random_state = 1)
model = model.fit(X_train, Y_train)



In [139]:
# check the accuracy on the training set
print(model.score(X_train, Y_train))

print(Y_train.mean())

0.6276111685625646
0.4788004136504654


In [140]:
dta = pd.read_csv("D:\MSc Computer Science - AR VR\Machine Learning\Twitter Gender Classification\ML-1819--task-107--team-32\ML-1819--task-107--team-32_cleanedUpDataTestSet.csv", ',')

In [141]:
Y_test = dta.iloc[:,1]
X_test = dta.iloc[:, 2:-1]

In [142]:
Y_test, X_test = dmatrices('gender ~ created + fav_number + tweet_count + descLen + des_hashtag_count + nameLen + tweet_length + '
                'num_tagged + tweet_hashtags + C(has_mentioned_other_bio) + C(uses_default_link_color) + '
                'C(tweet_has_link)', dta, return_type="dataframe")

In [143]:
Y_test = np.ravel(Y_test)

In [144]:
poly = PolynomialFeatures(2)
X_test = poly.fit_transform(X_test)
y_pred = model.predict(X_test)

In [145]:
model.score(X_test, Y_test)

0.6209677419354839

In [146]:
accuracy_score(Y_test, y_pred)

0.6209677419354839